# https://github.com/LemmyNet/lemmy-ui/issues/876

version: "3.6"

networks:
  lemmy-traefik-net:
    name: lemmy-traefik-net
    driver: bridge

services:
  # Balancer/Router
  balancer:
    image: balancer:local
    networks:
      - lemmy-traefik-net
    build:
      context: ./balancer
      dockerfile: Dockerfile
    environment:
      # for LetsEncrypt
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      TRAEFIK_ACME_CA_SERVER: ${TRAEFIK_ACME_CA_SERVER}

      # for CloudFlare DNS Validation
      CLOUDFLARE_EMAIL: ${TRAEFIK_CF_API_EMAIL:-""}
      CLOUDFLARE_DNS_API_TOKEN: ${TRAEFIK_CF_DNS_API_TOKEN:-""}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro" # mount the docker socket
      - "./volumes/balancer/certs:/certs"
      - "./volumes/balancer/logs/:/logs"
    ports:
      - "81:81" # Traefik Management
      - "82:82" # pgAdmin Container
      - "80:80"
      - "443:443"

  postgres:
    image: postgres:${PG_VERSION:-15-alpine}
    environment:
      - POSTGRES_USER=lemmy
      - POSTGRES_DB=lemmy
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
    networks:
      - lemmy-traefik-net
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
      - ./config/postgresql.conf:/etc/postgresql.conf
    restart: always

  pg_admin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_SERVER_JSON_FILE=/pgadmin4/lemmy-servers.json
    volumes:
      - ./config/servers.json:/pgadmin4/lemmy-servers.json
    networks:
      - lemmy-traefik-net

  pictrs:
    image: asonix/pictrs:${PICTRS_VERSION:-0.3.3}
    depends_on:
      - balancer
    user: 991:991
    networks:
      - lemmy-traefik-net
    environment:
      - PICTRS__SERVER__API_KEY=${PICTRS_API_KEY}
    volumes:
      - ./volumes/pictrs:/mnt
    restart: always
    mem_limit: 690m

  lemmy:
    image: dessalines/lemmy:${LEMMY_VERSION}
    command: /config/entrypoint.sh
    networks:
      - lemmy-traefik-net
    restart: always
    environment:
      #- RUST_LOG="warn,lemmy_server=debug,lemmy_api=debug,lemmy_api_common=debug,lemmy_api_crud=debug,lemmy_apub=debug,lemmy_db_schema=debug,lemmy_db_views=debug,lemmy_db_views_actor=debug,lemmy_db_views_moderator=debug,lemmy_routes=debug,lemmy_utils=debug,lemmy_websocket=debug"
      #- RUST_BACKTRACE=full

      - PICTRS_API_KEY=${PICTRS_API_KEY}
      - LEMMY_DOMAIN=${LEMMY_DOMAIN}
      - POSTGRES_PASS=${POSTGRES_PASS}
    volumes:
      - ./config:/user-config # maps the config dfirectory so we can check if there's a `lemmy.hjson` file there
      - ./config/config-entrypoint.sh:/config/entrypoint.sh
    depends_on:
      - balancer
      - postgres
      - pictrs
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=lemmy-traefik-net"
      - "traefik.http.services.lemmy.loadbalancer.server.port=8536"

      # Lemmy UI Internet HTTPS
      - "traefik.http.routers.lemmy_https_net.rule=Host(`${LEMMY_DOMAIN}`) && (
        (
        HeadersRegexp(`Accept`, `^application/.*$$`)
        ) ||
        (
        Method(`POST`)
        ) ||
        (
        PathPrefix(`/api`) ||
        PathPrefix(`/pictrs`) ||
        PathPrefix(`/feeds`) ||
        PathPrefix(`/nodeinfo`) ||
        PathPrefix(`/.well-known`)
        )
        )"
      - "traefik.http.routers.lemmy_https_net.entrypoints=https"
      - "traefik.http.routers.lemmy_https_net.tls.certResolver=cert_resolver"
      - "traefik.http.routers.lemmy_https_net.middlewares=secure_site@file,rate_limits@file"

      # Lemmy Internet HTTP Redirect
      - "traefik.http.routers.lemmy_http_redirect_net.rule=Host(`${LEMMY_DOMAIN}`)"
      - "traefik.http.routers.lemmy_http_redirect_net.entrypoints=http"
      - "traefik.http.routers.lemmy_http_redirect_net.middlewares=redirect_https@file"

  lemmy_ui:
    image: dessalines/lemmy-ui:${LEMMY_UI_VERSION}
    restart: always
    environment:
      - LEMMY_UI_LEMMY_INTERNAL_HOST=lemmy:8536
      - LEMMY_UI_LEMMY_EXTERNAL_HOST=${LEMMY_DOMAIN}
      - LEMMY_UI_HTTPS=false
    volumes:
      - ./volumes/lemmy-ui/extra_themes:/app/extra_themes
    depends_on:
      - balancer
      - lemmy
    networks:
      - lemmy-traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=lemmy-traefik-net"
      - "traefik.http.services.lemmy_ui.loadbalancer.server.port=1234"

      # Lemmy UI Internet HTTPS
      - "traefik.http.routers.lemmy_ui_https_net.rule=Host(`${LEMMY_DOMAIN}`) && !(
        (
        HeadersRegexp(`Accept`, `^application/.*$$`)
        ) ||
        (
        Method(`POST`)
        ) ||
        (
        PathPrefix(`/api`) ||
        PathPrefix(`/pictrs`) ||
        PathPrefix(`/feeds`) ||
        PathPrefix(`/nodeinfo`) ||
        PathPrefix(`/.well-known`)
        )
        )"
      - "traefik.http.routers.lemmy_ui_https_net.entrypoints=https"
      - "traefik.http.routers.lemmy_ui_https_net.tls.certResolver=cert_resolver"
      - "traefik.http.routers.lemmy_ui_https_net.middlewares=secure_site@file,rate_limits@file"

      # Lemmy Internet HTTP Redirect
      - "traefik.http.routers.lemmy_ui_http_redirect_net.rule=Host(`${LEMMY_DOMAIN}`)"
      - "traefik.http.routers.lemmy_ui_http_redirect_net.entrypoints=http"
      - "traefik.http.routers.lemmy_ui_http_redirect_net.middlewares=redirect_https@file"

  ## example mail forwarders

  ### postfix-relay

  # use one of these configs and update lemmy.hjson with appropriate smtp

  # using https://hub.docker.com/r/mwader/postfix-relay/
  # postfix:
  #   image: mwader/postfix-relay:latest
  #   restart: always
  #   networks:
  #     - lemmy-traefik-net # add to the lemmy network
  #   environment:
  #     - POSTFIX_myhostname=lemmy.tgxn.local
  #     # - OPENDKIM_DOMAINS=smtp.domain.tld
