# https://github.com/LemmyNet/lemmy-ui/issues/876

version: "2"

networks:
  traefik-net:
    external: true
  mail-net:
    external: true

  lemmy-net:
    driver: bridge
    internal: true
  out-net:
    driver: bridge

services:

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=lemmy
      - POSTGRES_DB=lemmy
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
    ports:
      - "5432:5432/tcp"
    networks:
      - out-net
      - lemmy-net
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql.conf
    restart: always
  
  pictrs:
    image: asonix/pictrs:0.3.3
    user: 991:991
    networks:
      - lemmy-net
    environment:
      - PICTRS__SERVER__API_KEY=${PICTRS_API_KEY}
    volumes:
      - ./volumes/pictrs:/mnt
    restart: always
    mem_limit: 690m

  lemmy:
    image: dessalines/lemmy:${LEMMY_VERSION}
    networks:
      - traefik-net
      - lemmy-net
      - mail-net
    restart: always
    environment:
      - RUST_LOG="warn,lemmy_server=debug,lemmy_api=debug,lemmy_api_common=debug,lemmy_api_crud=debug,lemmy_apub=debug,lemmy_db_schema=debug,lemmy_db_views=debug,lemmy_db_views_actor=debug,lemmy_db_views_moderator=debug,lemmy_routes=debug,lemmy_utils=debug,lemmy_websocket=debug"
      - RUST_BACKTRACE=full

    volumes:
      - ./lemmy.hjson:/config/config.hjson
    depends_on:
      - postgres
      - pictrs
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-net"

      - "traefik.http.services.lemmy.loadbalancer.server.port=8536"

      # internet https
      # - "traefik.http.routers.lemmy_https_net.rule=Host(`${LEMMY_DOMAIN}`)"

      # - "traefik.http.middlewares.lemmy_cors.headers.accesscontrolallowmethods=GET,OPTIONS,PUT"
      # - "traefik.http.middlewares.lemmy_cors.headers.accesscontrolalloworigin=*"
      # - "traefik.http.middlewares.lemmy_cors.headers.accesscontrolmaxage=100"
      # - "traefik.http.middlewares.lemmy_cors.headers.addvaryheader=true"

      - "traefik.http.routers.lemmy_https_net.rule=Host(`${LEMMY_DOMAIN}`) && (
                                                   (
                                                       HeadersRegexp(`Accept`, `^application/.*$$`)
                                                   ) ||
                                                   (
                                                       Method(`POST`)
                                                   ) ||
                                                   (
                                                       PathPrefix(`/api`) ||
                                                       PathPrefix(`/pictrs`) ||
                                                       PathPrefix(`/feeds`) ||
                                                       PathPrefix(`/nodeinfo`) ||
                                                       PathPrefix(`/.well-known`)
                                                   )
                                               )"

      - "traefik.http.routers.lemmy_https_net.entrypoints=https"
      - "traefik.http.routers.lemmy_https_net.tls.certResolver=tgxn_net"
      - "traefik.http.middlewares.cors_headers.headers.customResponseHeaders.Access-Control-Allow-Origin=*"
      - "traefik.http.routers.lemmy_https_net.middlewares=cors_headers@file"

      # internet http redirect
      - "traefik.http.routers.lemmy_http_redirect_net.rule=Host(`${LEMMY_DOMAIN}`)"
      - "traefik.http.routers.lemmy_http_redirect_net.entrypoints=http"
      - "traefik.http.routers.lemmy_http_redirect_net.middlewares=redirect_https@file"

  lemmy_ui:
    image: dessalines/lemmy-ui:${LEMMY_VERSION}
    # ports:
    #   - "127.0.0.1:${LEMMY_UI_PORT}:1234"
    restart: always
    environment:
      - LEMMY_UI_LEMMY_INTERNAL_HOST=lemmy:8536
      - LEMMY_UI_LEMMY_EXTERNAL_HOST=${LEMMY_DOMAIN}
      - LEMMY_UI_HTTPS=false
    volumes:
      - ./volumes/lemmy-ui/extra_themes:/app/extra_themes
    depends_on: 
      - lemmy
    networks:
      - traefik-net
      - lemmy-net
      - mail-net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-net"

      - "traefik.http.services.lemmy_ui.loadbalancer.server.port=1234"

      # internet https
      # - "traefik.http.routers.lemmy_https_net.rule=Host(`${LEMMY_DOMAIN}`)"

      - "traefik.http.routers.lemmy_ui_https_net.rule=Host(`${LEMMY_DOMAIN}`) && !(
                                                   (
                                                       HeadersRegexp(`Accept`, `^application/.*$$`)
                                                   ) ||
                                                   (
                                                       Method(`POST`)
                                                   ) ||
                                                   (
                                                       PathPrefix(`/api`) ||
                                                       PathPrefix(`/pictrs`) ||
                                                       PathPrefix(`/feeds`) ||
                                                       PathPrefix(`/nodeinfo`) ||
                                                       PathPrefix(`/.well-known`)
                                                   )
                                               )"

      - "traefik.http.routers.lemmy_ui_https_net.entrypoints=https"
      - "traefik.http.routers.lemmy_ui_https_net.tls.certResolver=tgxn_net"
      - "traefik.http.routers.lemmy_ui_https_net.middlewares=cors_headers@file"

      # internet http redirect
      - "traefik.http.routers.lemmy_ui_http_redirect_net.rule=Host(`${LEMMY_DOMAIN}`)"
      - "traefik.http.routers.lemmy_ui_http_redirect_net.entrypoints=http"
      - "traefik.http.routers.lemmy_ui_http_redirect_net.middlewares=redirect_https@file"
