#!/bin/sh

USER_CONFIG=/userConf/lemmy.hjson
LEMMY_CONFIG=/config/config.hjson

# This manufactures a config file for Lemmy from environment variables.

if [ -e $USER_CONFIG ]
then
  echo "ok, config located"
else

echo "no config found, creating one"

cat >$USER_CONFIG <<EOL
# this file was generated by config-entrypoint.sh
# it will not be generated as long as one is found in /userConf
{
    database: {
      host: postgres
      password: "POSTGRES_PW"
      pool_size: 25
    }
    hostname: "BASE_URL"
    port: 8536,
    pictrs: {
      url: "http://pictrs:8080/"
      api_key: "PICTRS_API_KEY"
    }
}
EOL

sed -i "s/POSTGRES_PW/$POSTGRES_PASS/g" $USER_CONFIG
sed -i "s/BASE_URL/$LEMMY_DOMAIN/g" $USER_CONFIG
sed -i "s/PICTRS_API_KEY/$PICTRS_API_KEY/g" $USER_CONFIG

fi

# copy to lemmy config
echo "Installing config"
cp $USER_CONFIG $LEMMY_CONFIG

# Start Normal Lemmy Server
/app/lemmy
