http:

  # Redirect to https
  middlewares:
    
    redirect_https:
      redirectScheme:
        scheme: https
        permanent: true
    
    lemmy_site:
      headers:
        stsIncludeSubdomains: false
        stsPreload: true
        stsSeconds: 31536000
        isDevelopment: false
        customResponseHeaders:
          server: ""
        frameDeny: true
        browserXssFilter: true
      rateLimit:
        average: 100
        burst: 50


  routers:

    traefik:
      service: api@internal
      entryPoints:
        - traefik
      priority: 1
      rule: "PathPrefix(`/`)"

    pg_admin:
      service: pg_admin
      entryPoints:
        - pg_admin
      rule: "PathPrefix(`/`)"

  services:

    pg_admin:
      loadBalancer:
        servers:
          - url: "http://pg_admin"
